version: "3"
services:
  developing:
    build: docker/developing
    volumes:
      - .:/var/app
  fedora:
    build: docker/fedora
    image: imagick_fedora
    volumes:
      - .:/home/app
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
